spring:
  application:
    name: ccshub

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.vjcyyzpskoqhdkqklttm&password=ccsHub_Systemintegration123
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  jpa:
    show-sql: true
    hibernate:
      ddl_auto: none

  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: "https://login.microsoftonline.com/823cde44-4433-456d-b801-bdf0ab3d41fc/v2.0"
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: 67761468-57d5-41a3-9b4f-1f69101be135
            client-secret: JDb8Q~9YR51YTnNtJNDz6Y3nhX2CIHHnyjmqdbvf
            scope:
              - openid
              - email
              - profile
              - api://67761468-57d5-41a3-9b4f-1f69101be135/user_impersonation
      resourceserver:
        jwt:
          issuer-uri: "https://login.microsoftonline.com/823cde44-4433-456d-b801-bdf0ab3d41fc/v2.0"
          jwk-set-uri: "https://login.microsoftonline.com/823cde44-4433-456d-b801-bdf0ab3d41fc/discovery/v2.0/keys"

server:
  port: 8080
  address: localhost
  error:
    include-stacktrace: never